import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Sidebar from "./components/Sidebar";
import LeftSide from "./components/LeftSide";
import MainPage from "./components/MainPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head dangerouslyForceHydrate>
        <title>Nft Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#EBF1F5] h-screen flex">
        <aside>
          <Sidebar />
        </aside>
        <div className="w-[70%]">
          <MainPage />
        </div>
        <aside className="bg-white w-[25%] p-5">
          <LeftSide />
        </aside>
      </main>
    </>
  );
}
